Django_REST/chart/urls.py
from django.urls import path

from . import views

app_name ='chart'

urlpatterns = [
    path('', views.index, name='index'),
    path('chart_data/<slug:country>', views.Chart_data.as_view()),
    path('chart_data_elastic/<slug:country>', views.Chart_data_elastic.as_view()),
]

Django_REST/cmpdetails/urls.py
from django.urls import path

from . import views

app_name='cmpdetails'

urlpatterns = [
    path('', views.index, name='index'),
    path('cmp_details/', views.cmp_details , name='cmp_details'),
    path('<int:comp_id>/',views.emp_details, name='emp_details'),
    path('<int:comp_id>/<int:emp_id>/',views.emp_delete, name='emp_delete'),
    path('<int:comp_id>/<int:emp_id>/emp_update',views.emp_update, name='emp_update'),
    path('<int:emp_id>/emp_update',views.emp_update_save, name='emp_update_save'),
    path('cmp_details/<int:comp_id>/add_new_emp_pg',views.add_new_emp_pg,name='add_new_emp_pg'),
    path('cmp_details/<int:comp_id>/emp_add_new',views.emp_add_new,name='emp_add_new'),
]

Django_REST/compinfosite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('cmpdetails/', include('cmpdetails.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('chart/', include('chart.urls')),
]

Django_REST/dashboard/urls.py
from django.urls import path

from . import views

app_name='dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('cluster/<int:cluster_id>/', views.edit_cluster, name='edit_cluster'),
    path('cluster/<int:cluster_id>/save', views.save_cluster, name='save_cluster'),
    path('REST_API/', views.dashboard_rest, name='dashboard_rest'),
    path('detail/<int:cluster_id>', views.dashboard_detail_rest, name='dashboard_detail_rest'),
    path('cluster_list/', views.ClusterList.as_view(), name='ClusterList'),
    path('cluster_elastic_REST/', views.ClusterElastic.as_view(), name='Clusterelastic'),
    path('cluster_elastic/', views.index_elastic, name='index_elastic'),
    path('cluster_elastic/<int:cluster_id>/', views.edit_cluster_elastic, name='edit_cluster_elastic'),
    path('cluster_elastic/<int:cluster_id>/save', views.save_cluster, name='save_cluster_elastic'),

]

Django_REST/login/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views as local_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'template_name': 'logged_out.html'}, name='logout'),
    path('myapps/', local_views.myapps, name='myapps'),
]

Django_REST/login/models.py
from django.db import models

# Create your models here.

Django_REST/login/views.py
from django.shortcuts import render

# Create your views here.


def myapps(request):
    return render(request,'Myapps.html')

Django_REST/login/templates/Myapps.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <span> My Projects</span>
    <ul>
        <li><a href="{% url 'cmpdetails:index'%}" >HR Management System </a> </li>
        <li><a href="{% url 'dashboard:index'%}" >Cluster Dashboard</a></li>
        <li><a href="{% url 'dashboard:index_elastic'%}" > Cluster Dashboard(elastic)</a></li>
        <li><a href="{% url 'chart:index'%}" >COVID19 chart</a></li>


    </ul>

</div>

</body>
</html>

Django_REST/login/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Dashboard Login{% endblock %}</title>
</head>
<body>
  <header>
    <h1>Login</h1>
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'logout' %}">logout</a>
    {% else %}
      <a href="{% url 'login' %}">login</a>
    {% endif %}
  </header>
  <main>
    {% block content %}
      {% if user.is_authenticated %}
        <p>logged in successfully!</p>
      {% else %}
        <p>logged out successfully!</p>
      {% endif %}
    {% endblock %}
  </main>
</body>
</html>

Django_REST/login/templates/home.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% endblock %}